# Generated by Django 4.0.2 on 2022-02-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.CharField(default='611ba5e1f4969d97724190839eb959c2', max_length=255),
        ),
    ]
