# Generated by Django 4.0.2 on 2022-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_wallet', '0002_alter_transaction_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('FAILED', 'FAILED'), ('INITIALIZED', 'INITIALIZED'), ('CONFIRM', 'CONFIRM'), ('VERIFY', 'VERIFY'), ('CANCEL', 'CANCEL'), ('EXPIRE', 'EXPIRE'), ('COMPLETED', 'COMPLETED')], default='INITIALIZED', editable=False, max_length=20),
        ),
    ]
